### ISSUE TITLE
Home fragment not working for android?

### ISSUE THREAD

**Issue by gkaldev** [firebase/friendlypix-android#24]
_From @asbadve on July 17, 2016 6:43_

It shows nothing all other parts are working except Home fragment for android sample.

_Copied from original issue: firebase/friendlypix#26_

**Comment by gkaldev** [comment]
_From @Divala on November 5, 2016 6:41_

Facing the same problem. Anyone to help?

**Comment by gkaldev** [comment]
_From @patricknasc on December 21, 2016 1:1_

I will code this for us!

**Comment by gkaldev** [comment]
_From @Divala on December 21, 2016 5:25_

Okay thanks

**Comment by gkaldev** [comment]
_From @migueltarga on December 30, 2016 18:29_

#65

**Comment by gkaldev** [comment]
_From @v3dinc on July 7, 2017 19:51_

1.

**Comment by gkaldev** [comment]
Cleaning up issue fixed in upcoming v2.

**Comment by samuual** [comment]
if it's fixed in V2 when can we see V2? can you give early access to a fix for this?

**Comment by horgag1** [comment]
when can we expect to see version 2!? 

Thanks :)
