### ISSUE TITLE
Commit Message : Initial WIP commit to get code into VCS.

### ISSUE THREAD

**Issue by gkaldev** [firebase/friendlypix-android#25]
_From @antonio-eggberg on June 12, 2016 1:34_

Hi, 

For my local repo can I delete all the files from "Initial WIP commit to get code into VCS."? will it be ok? I just want to remove files that are not being used at all. 

thanks.

_Copied from original issue: firebase/friendlypix#18_

**Comment by gkaldev** [comment]
_From @nicolasgarnier on June 16, 2016 10:29_

Yes the blobserver directory is not used at this point you can remove it.

**Comment by gkaldev** [comment]
_From @nicolasgarnier on June 16, 2016 10:30_

Hey @gkaldevrel is it OK to delete the `blobserver` directory? Not sure what it's used for but it seems it;s not needed?

**Comment by gkaldev** [comment]
Yeah, it's safe to delete. I was just using it before we incorporated storage. I was going to delete it in my next commit, but feel free to do it earlier if you want.

**Comment by nicolasgarnier** [comment]
Ps: this was deleted. You can close.
